name: 🔆Dynamic Matrix API Demo

on:
  workflow_dispatch:
    inputs:
      runner:
        description: "Select the Runner"
        required: true
        default: "windows-latest"
        type: choice
        options:
          - windows-latest
          - Dev-runner
          - qa-runner
          - mock-runner
          - prod-runner
      environment:
        description: "Select the Target"
        required: true
        default: "Environment"
        type: choice
        options:
          - dev
          - qa
          - mock
          - prod
      tagName:
        description: "Select the Job"
        required: true
        type: choice
        options:
          - RCM-AHI.APP.LEGACY
          - RCM-AHI.APP.PHASE2
 
env:
  ENV_NAME: ${{github.event.inputs.environment}}
  targetmachine: ""
  Runner: ${{ github.event.inputs.environment =='dev' && 'ahiqa-dev' || (github.event.inputs.environment  =='qa' && 'windows-latest' || ( github.event.inputs.environment=='mock' && 'ubuntu-latest' || 'windows-latest'))}}
jobs:
  Wait-for-Approval:
    runs-on: ${{ github.event.inputs.environment =='dev' && 'ahiqa-dev' || (github.event.inputs.environment  =='qa' && 'windows-latest' || ( github.event.inputs.environment=='mock' && 'ubuntu-latest' || 'windows-latest'))}}
    environment:
      name: approval-check
    steps:
    - name: Approval step
      run: echo "This is the approval-check environment"
  Initialize:
    runs-on: ${{ github.event.inputs.environment =='dev' && 'ahiqa-dev' || (github.event.inputs.environment  =='qa' && 'windows-latest' || ( github.event.inputs.environment=='mock' && 'ubuntu-latest' || 'windows-latest'))}}
    needs: Wait-for-Approval
    environment: 
      name: ${{ github.event.inputs.environment}}
    outputs:
      output1: ${{ steps.set-matrix.outputs.targetmachine }}
    steps:
      - name: Generate Target Machines
        id: set-matrix
        shell: pwsh
        run: |
          echo "${{ vars.ENV_NAME}}"
           echo "${{ env.ENV_NAME}}"
          echo "${{ env.TEST}}"
          echo "${{vars.TEST}}"
          echo "$test"
          echo "${{vars.test}}"
          $region= ${{env.region}}
          $targetmachine = @()
 
          if ("${{ github.event.inputs.tagName }}" -eq "RCM-AHI.APP.LEGACY") {
            if ("${{ github.event.inputs.environment }}" -eq "prod") {
              $targetmachine += '"i-0b1d3c4e2a5f7e9b6,imp_app_aps_server1,Production"'
              $targetmachine += '"i-0b1d3c4e2a5f7e9b6,imp_app_aps_server2,Production"'
            } elseif ("${{ github.event.inputs.environment }}" -eq "dev") {
              $targetmachine = '"i-0b1d3c4e2a5f7e9b6,imp_app_aps_server1,Development"'
            } elseif ("${{ github.event.inputs.environment }}" -eq "qa") {
              $targetmachine = '"i-0b1d3c4e2a5f7e9b6,imp_app_aps_server1,QA"'
            } elseif ("${{ github.event.inputs.environment }}" -eq "mock") {
              $targetmachine = '"i-0b1d3c4e2a5f7e9b6,imp_app_aps_server1,Mock"'
            }
          } 
          elseif ("${{ github.event.inputs.tagName }}" -eq "RCM-AHI.APP.PHASE2") {
            if ("${{ github.event.inputs.environment }}" -eq "dev") {
              $targetmachine += '"i-0b1d3c4e2a5f7e9b6,imp_app_aps_server2,Phase2"'
            }
          }
 
          # Convert to JSON and set output
          #$jo = ($targetmachine | ConvertTo-Json).Trim() -replace '\s+', ''
          $jo = "[" + ($targetmachine -join ",") + "]"
          Write-Host "Target Machines JSON: $jo"
          echo "targetmachine=$jo" >> $env:GITHUB_OUTPUT
          Write-Host "GITHUB_OUTPUT:"
          Get-Content $env:GITHUB_OUTPUT
 
  deploy:
    runs-on: ${{ inputs.runner }}
    needs: Initialize
    strategy:
      matrix:
        target: ${{ fromJson(needs.Initialize.outputs.output1) }}
    steps:
    #  - name: Debug Matrix Value
    #    run: echo "Deploying to target: ${{ matrix.target }}"
 
      - name: Wait for Approval
        run: echo "Waiting for approval..."
 
      - name: Deploy Service
        run: |
          echo "${{vars.test}}"
          echo "Deploying to ${{ matrix.target }}"
          # Add your deployment logic here

  deploy2:
    runs-on: ${{ inputs.runner }}
    needs: [deploy]
    
    steps:
    #  - name: Debug Matrix Value
    #    run: echo "Deploying to target: ${{ matrix.target }}"
 
      - name: script-output
        uses: actions/github-script@v6
        with:
          script: |
            const octokit = new Octokit({
              auth: "${{GITHUB.TOKEN}}"
            })
            
            output = await octokit.request('GET /repos/{owner}/{repo}/environments/{environment_name}/variables', {
              owner: 'peeyushtrivedi0706',
              repo: 'runnerlinuxtest',
              environment_name: 'QA',
              headers: {
                'X-GitHub-Api-Version': '2022-11-28'
              }
            })
            core.setOutput('my_output', output);
            
 
      - name: Deploy Service
        run: |
          echo "${{env.test}}"
          echo "Deploying to ${{ matrix.target }}"
          echo "Output from script: ${{ steps.script-output.outputs.my_output }}"
          # Add your deployment logic here
