# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      runner:
        description: "Select the Runner"
        required: true
        default: "Environment"
        type: choice
        options:
          - windows-latest
          - Dev-ruuner
          - qa-rrunner
      environment:
        description: "Select the Target"
        required: true
        default: "Environment"
        type: choice
        options:
          - imp
      jobName:
        description: "Select the Job"
        required: true
        type: choice
        options:
          - ams_aps
          - ams_prt
          - ams_rc4_api
          - ams_tools
          - ams_web
          - Start All
          - Stop All


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      
      # Runs a single command using the runners shell
      - name: Echo hostname of runner
        run: hostname
      - name: checkout
        uses: actions/checkout@v4
      - name: reuse
        uses: ./.github/workflows/ams_prt.yaml
        with:
          environment: ${{ github.event.inputs.environment }}
          runner: ${{ github.event.inputs.runner }}
          servicetag: "CORE.IMP-APP-PRT"
          Targets: "ts"
    
  ams_aps:
    if: (${{github.event.inputs.jobName}} == 'ams_aps')
    strategy:
      matrix:
        target: ["i-0463aee569e9ecce8 - imp_app_aps_server-2 #Production", "i-0760b1d479570257d - imp_app_aps_server-1 #Production"]
    uses: ./.github/workflows/ams_aps.yaml
    with:
          environment: ${{ github.event.inputs.environment }}
          runner: ${{ github.event.inputs.runner }}
          servicetag: "CORE.IMP-APP-PRT"
          Targets: ${{ matrix.target }}

  ams_prt:
    if: (${{github.event.inputs.jobName}} == 'ams_aps')
    strategy:
      matrix:
        target: ["i-0463aee569e9ecce8 - imp_app_aps_server-2 #Production", "i-0760b1d479570257d - imp_app_aps_server-1 #Production"]
    uses: ./.github/workflows/ams_prt.yaml
    with:
          environment: ${{ github.event.inputs.environment }}
          runner: ${{ github.event.inputs.runner }}
          servicetag: "CORE.IMP-APP-PRT"
          Targets: ${{ matrix.target }}
         
