# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      runner:
        description: "Select the Runner"
        required: true
        default: "Environment"
        type: choice
        options:
          - windowss-latest
          - Dev-ruuner
          - qa-rrunner
      environment:
        description: "Select the Target"
        required: true
        default: "Environment"
        type: choice
        options:
          - imp
      jobName:
        description: "Select the Job"
        required: true
        type: choice
        options:
          - ams_aps
          - ams_prt
          - ams_rc4_api
          - ams_tools
          - ams_web
          - Start All
          - Stop All


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      
      # Runs a single command using the runners shell
      - name: Echo hostname of runner
        run: hostname
      # Create Session
      - name: Run a one-line script
        run: $Server01 = New-PSSession -ComputerName ip-172-31-85-161.ec2.internal

      # echo hostname of remote serverl
      - name: Run a one-line script
        run: |
         Enter-PSSession -Session $Server01
         hostname

      # List and create dir on host server
      - name: Loat and create dir on remote server
        run: I
          ls c:\
          mkdir test.
          Exit-PSSession
